FROM python:3

LABEL COPYRIGHT="(c) 2023 ACME"

RUN apt-get -y update && \
    apt-get install -y zip unzip

# Install chromedriver
RUN wget -N https://chromedriver.storage.googleapis.com/72.0.3626.69/chromedriver_linux64.zip -P ~/
RUN unzip ~/chromedriver_linux64.zip -d ~/
RUN rm ~/chromedriver_linux64.zip
RUN mv -f ~/chromedriver /usr/local/bin/chromedriver
RUN chown root:root /usr/local/bin/chromedriver
RUN chmod 0755 /usr/local/bin/chromedriver

# Install chrome broswer
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get -y update && \
    apt-get -y install google-chrome-stable

# Install Requirements
ENV APPPATH /app
COPY requirements.txt ${APPPATH}/requirements.txt 
RUN pip --disable-pip-version-check install -r ${APPPATH}/requirements.txt